### ISSUE TITLE
Elemental Bolts/Arrows have some typos

### ISSUE THREAD

**Issue by porkchop-sandwiches** [Argent77/A7-ImprovedArcher#5]
The Elemental Bolt items stored in a7#inro1.itm through a7#inro5.itm are set to d6 damage dice rather than d8.

Also the charges for Elemental Bolt/Arrow 1 - 5 are always set to 20.  The description indicates they should double in charges at level 8 and level 16 (which would impact itm files 2-4 I believe).  Not sure if that means 40 then 80 or what you intended but all of them are the same currently.

I didn't check the other summoned ammo types such as Reinforced/Blessed/Endowed as I'm only playing an Archer so you may want to look over those too.

**Comment by Argent77** [comment]
Thank you. Base damage of bolts is indeed incorrect. Will be fixed.

The item charges should be alright. The number of charges for spell-created ammo is defined by the spell effect, which overrides the charges of the item.

**Comment by Argent77** [comment]
Fixed: 7b291cd8db00d71b9999a304df511a0854b65b7e
